### ISSUE TITLE
Understanding output

### ISSUE THREAD

**Issue by msegala** [isakkarlsson/ucr-suite-2d#1]
Nice code. Can you please verify my understanding on how you extending this to two dimensions. 

It seems that you just took 
distA = dtw(dimension 1)
distB = dtw(dimension 2)
dtw_distance = distA + distB

Is this correct? If so, is it standard practice to just dimensions as independent?
Thanks!

**Comment by isaksamsten** [comment]
Your understanding is correct. I would not consider it standard practice, merely one possible way. Another possible option is to do the neighbour search independently for each dimension and let them vote. The application domain can be the judge here.

**Comment by isaksamsten** [comment]
A possible reference: On the Non-Trivial Generalization of Dynamic Time Warping to the Multi-Dimensional Case (http://epubs.siam.org/doi/abs/10.1137/1.9781611974010.33)
